STEP 1: Getting to know the data

In [64]:
import pandas as pd

In [65]:
import csv

In [66]:
# First 10 rows
df = pd.read_csv(r'd:\PythonCourse_MAAB\project\super_dirty_students_data.csv')
df.head(10)

,student_id,name,age,gender,score,phone,city,email,date_of_join,course,attendance,status,gpa,remarks,money_spent,event_time,address_raw,profile_json
0,1,Claudia Short,20,NaN,NaN,+1-619-379-4152x102,Katieland,someonegmail.com,1662247364,Data Science,NaN,active,3.72,good,$135,1629312830,"Apartment 37, South Kevin district, Tashkent, ...","{'hobbies': ['gun', 'nice'], 'skills': {'tech'..."
1,2,NaN,20,Female,ninety,NaN,Dawnburgh,psmith@chen.com,2017/08/29,Data Science,NaN,active,1.88,excellent,$152,11/10/2001 04:19 AM,UZ 100332 Tashkent South Patricia,"{hobbies:['against', 'good']}"
2,3,Kathryn Moyer,20,NaN,ninety,NaN,Lake Stevenmouth,NaN,2017-08-14,DATA SCIENCE,NaN,pending,NaN,excellent,185.0,1657837622,"Wendyshire 12-kv, dom 1, Tashkent","{'hobbies': ['fast', 'clearly'], 'skills': {'t..."
3,4,Ruben Wilson,twenty,fmale,81,NaN,Port Pamelafort,special,1973-09-17,data-sciens,NaN,inactive,0,good,175 USD,1682795130,"Apartment 16, North Tamara district, Tashkent,...","{'hobbies': ['left', 'role'], 'skills': {'tech..."
4,5,Robert Pruitt,20,Female,NaN,001-182-659-5631x02803,Kingburgh,six,2023/11/25,data_sciense,NaN,pending,4.37,average,$282,2013-10-13,"BROKEN,ADDRESS,DATA,,,","{'hobbies': ['sort', 'science'], 'skills': {'t..."
5,6,David Martinez,20,Male,ninety,001-074-828-6016x937,Hugheshaven,nathangibbs@hotmail.com,1603493647,DATA SCIENCE,110,pending,15.5,average,"85,00",1983-04-30T01:46:36,"Apartment 42, North Jamesfurt district, Tashke...","{hobbies:['order', 'keep']}"
6,7,NaN,18 years,FEMALE,71,314.018.0928x3134,Sharpfurt,nguyenlisa@@horn.org,1982-01-16,data science,NaN,active,0,excellent,275.0,19/11/2004 11:42 PM,"Lake Tracishire 29-kv, dom 8, Tashkent","{'hobbies': ['fall', 'teacher'], 'skills': {'t..."
7,8,Nicholas Dennis,21,FEMALE,ninety,8091556011,Matthewfort,avoid,2000.06.26,python,63,active,four point five,excellent,135,1978/09/23,"70576 Butler Harbor Suite 847, Janetberg",INVALID_JSON_DATA
8,9,NaN,twenty,fmale,77,854-964-5423,South Paulchester,stacysmith@taylor.biz,2000-03-15,ds,110%,active,15.5,excellent,104 USD,1995-10-20,"Williamsborough 2-kv, dom 18, Tashkent","{'hobbies': ['require', 'open'], 'skills': {'t..."
9,10,Elizabeth Villegas,22,femlae,NaN,(205)467-4476x0583,South Dianatown,anthonywalker@@gmail.com,2013-02-11T07:12:29,data_sciense,99,inactive,"3,7",average,"215,00",2014-12-16T06:44:51,"BROKEN,ADDRESS,DATA,,,","{'hobbies': ['management', 'to'], 'skills': {'..."

In [67]:
# Column names
df.columns

Index(['student_id', 'name', 'age', 'gender', 'score', 'phone', 'city',
       'email', 'date_of_join', 'course', 'attendance', 'status', 'gpa',
       'remarks', 'money_spent', 'event_time', 'address_raw', 'profile_json'],
      dtype='str')

In [68]:
# Number of Columns
len(df.columns)

18

In [7]:
# Shape (rows, columns)
df.shape

(1000, 18)

In [69]:
df.isnull()

,student_id,name,age,gender,score,phone,city,email,date_of_join,course,attendance,status,gpa,remarks,money_spent,event_time,address_raw,profile_json
0,False,False,False,True,True,False,False,False,False,False,True,False,False,False,False,False,False,False
1,False,True,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False
2,False,False,False,True,False,True,False,True,False,False,True,False,True,False,False,False,False,False
3,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False
4,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,False,False,False,False,True,True,False,False,False,False,True,False,True,False,False,False,False,False
996,False,False,False,True,True,False,False,False,False,False,True,False,False,True,False,False,False,False
997,False,True,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
999,False,True,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [8]:
# Number of missing values in each comlumn
df.isnull().sum()

student_id        0
name            335
age             108
gender          219
score           246
phone           371
city              0
email           151
date_of_join      0
course            0
attendance      326
status            0
gpa             141
remarks         204
money_spent       0
event_time        0
address_raw       0
profile_json      0
dtype: int64

In [9]:
# Understanding the type of data
df.dtypes

student_id      int64
name              str
age               str
gender            str
score             str
phone             str
city              str
email             str
date_of_join      str
course            str
attendance        str
status            str
gpa               str
remarks           str
money_spent       str
event_time        str
address_raw       str
profile_json      str
dtype: object

In [70]:
df.head(15)

,student_id,name,age,gender,score,phone,city,email,date_of_join,course,attendance,status,gpa,remarks,money_spent,event_time,address_raw,profile_json
0,1,Claudia Short,20,NaN,NaN,+1-619-379-4152x102,Katieland,someonegmail.com,1662247364,Data Science,NaN,active,3.72,good,$135,1629312830,"Apartment 37, South Kevin district, Tashkent, ...","{'hobbies': ['gun', 'nice'], 'skills': {'tech'..."
1,2,NaN,20,Female,ninety,NaN,Dawnburgh,psmith@chen.com,2017/08/29,Data Science,NaN,active,1.88,excellent,$152,11/10/2001 04:19 AM,UZ 100332 Tashkent South Patricia,"{hobbies:['against', 'good']}"
2,3,Kathryn Moyer,20,NaN,ninety,NaN,Lake Stevenmouth,NaN,2017-08-14,DATA SCIENCE,NaN,pending,NaN,excellent,185.0,1657837622,"Wendyshire 12-kv, dom 1, Tashkent","{'hobbies': ['fast', 'clearly'], 'skills': {'t..."
3,4,Ruben Wilson,twenty,fmale,81,NaN,Port Pamelafort,special,1973-09-17,data-sciens,NaN,inactive,0,good,175 USD,1682795130,"Apartment 16, North Tamara district, Tashkent,...","{'hobbies': ['left', 'role'], 'skills': {'tech..."
4,5,Robert Pruitt,20,Female,NaN,001-182-659-5631x02803,Kingburgh,six,2023/11/25,data_sciense,NaN,pending,4.37,average,$282,2013-10-13,"BROKEN,ADDRESS,DATA,,,","{'hobbies': ['sort', 'science'], 'skills': {'t..."
5,6,David Martinez,20,Male,ninety,001-074-828-6016x937,Hugheshaven,nathangibbs@hotmail.com,1603493647,DATA SCIENCE,110,pending,15.5,average,"85,00",1983-04-30T01:46:36,"Apartment 42, North Jamesfurt district, Tashke...","{hobbies:['order', 'keep']}"
6,7,NaN,18 years,FEMALE,71,314.018.0928x3134,Sharpfurt,nguyenlisa@@horn.org,1982-01-16,data science,NaN,active,0,excellent,275.0,19/11/2004 11:42 PM,"Lake Tracishire 29-kv, dom 8, Tashkent","{'hobbies': ['fall', 'teacher'], 'skills': {'t..."
7,8,Nicholas Dennis,21,FEMALE,ninety,8091556011,Matthewfort,avoid,2000.06.26,python,63,active,four point five,excellent,135,1978/09/23,"70576 Butler Harbor Suite 847, Janetberg",INVALID_JSON_DATA
8,9,NaN,twenty,fmale,77,854-964-5423,South Paulchester,stacysmith@taylor.biz,2000-03-15,ds,110%,active,15.5,excellent,104 USD,1995-10-20,"Williamsborough 2-kv, dom 18, Tashkent","{'hobbies': ['require', 'open'], 'skills': {'t..."
9,10,Elizabeth Villegas,22,femlae,NaN,(205)467-4476x0583,South Dianatown,anthonywalker@@gmail.com,2013-02-11T07:12:29,data_sciense,99,inactive,"3,7",average,"215,00",2014-12-16T06:44:51,"BROKEN,ADDRESS,DATA,,,","{'hobbies': ['management', 'to'], 'skills': {'..."
10,11,Shawn Baker,19,NaN,NaN,9868509629,Zhangstad,stand,2025-06-10,data science,110%,active,"3,7",excellent,"183,00",2001-06-06T05:29:47,"Apartment 34, North Samantha district, Tashken...",INVALID_JSON_DATA
11,12,NaN,18,femlae,71,NaN,Austinside,annalee@@gmail.com,14/01/2013 07:16 PM,d.s.,110%,inactive,-2,average,208,2003-05-27,"Apartment 13, Morrismouth district, Tashkent, ...","{hobbies:['forward', 'like']}"
12,13,NaN,19,fmale,ninety,(223)573-6311x916,Lesliefurt,someonegmail.com,2014-12-24,data science,110,inactive,four point five,excellent,84.0,2010/11/21,"Frankchester 9-kv, dom 20, Tashkent",INVALID_JSON_DATA
13,14,Thomas Prince,20,NaN,NaN,NaN,East Michellestad,aphillips@holland-diaz.org,2012-02-09,PYTHNO,114,inactive,15.5,excellent,210 USD,2013.05.14,UZ 100394 Tashkent Stevensborough,"{hobbies:['understand', 'become']}"
14,15,NaN,21,MALE,73,NaN,Michellebury,kevin65@maxwell.info,1971-03-17T08:30:18,python,110%,pending,"3,7",good,$191,1984-10-29T14:14:47,"Davidborough 9-kv, dom 29, Tashkent",INVALID_JSON_DATA

STEP 2: Simple string cleaning

In [ ]:
# Removing scpace in each string column using strip()
df = df.apply(lambda col: col.str.strip() if col.dtype == 'object' else col)
df

,student_id,name,age,gender,score,phone,city,email,date_of_join,course,attendance,status,gpa,remarks,money_spent,event_time,address_raw,profile_json
0,1,Claudia Short,20,NaN,NaN,+1-619-379-4152x102,Katieland,someonegmail.com,1662247364,Data Science,NaN,active,3.72,good,$135,1629312830,"Apartment 37, South Kevin district, Tashkent, ...","{'hobbies': ['gun', 'nice'], 'skills': {'tech'..."
1,2,NaN,20,Female,ninety,NaN,Dawnburgh,psmith@chen.com,2017/08/29,Data Science,NaN,active,1.88,excellent,$152,11/10/2001 04:19 AM,UZ 100332 Tashkent South Patricia,"{hobbies:['against', 'good']}"
2,3,Kathryn Moyer,20,NaN,ninety,NaN,Lake Stevenmouth,NaN,2017-08-14,DATA SCIENCE,NaN,pending,NaN,excellent,185.0,1657837622,"Wendyshire 12-kv, dom 1, Tashkent","{'hobbies': ['fast', 'clearly'], 'skills': {'t..."
3,4,Ruben Wilson,twenty,fmale,81,NaN,Port Pamelafort,special,1973-09-17,data-sciens,NaN,inactive,0,good,175 USD,1682795130,"Apartment 16, North Tamara district, Tashkent,...","{'hobbies': ['left', 'role'], 'skills': {'tech..."
4,5,Robert Pruitt,20,Female,NaN,001-182-659-5631x02803,Kingburgh,six,2023/11/25,data_sciense,NaN,pending,4.37,average,$282,2013-10-13,"BROKEN,ADDRESS,DATA,,,","{'hobbies': ['sort', 'science'], 'skills': {'t..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Gary Sawyer,22,fmale,NaN,NaN,Gabriellefurt,amy97@woodard.net,1992.11.13,DATA SCIENCE,NaN,inactive,NaN,excellent,$64,14/10/2007 06:53 PM,"Apartment 12, Laurenhaven district, Tashkent, ...","{'hobbies': ['collection', 'his'], 'skills': {..."
996,997,Scott Clark,20,NaN,NaN,001-205-065-8737,Rogerborough,katiepage@hensley.com,2024.10.05,DATA SCIENCE,NaN,pending,"3,7",NaN,143,2021-06-21T07:46:27,"Patrickmouth 4-kv, dom 6, Tashkent",INVALID_JSON_DATA
997,998,NaN,20,MALE,NaN,264-577-8585,South Mary,someonegmail.com,19/11/2021 02:23 AM,data_sciense,95,inactive,-2,excellent,79.0,1975/05/11,"Apartment 38, New Brendan district, Tashkent, ...","{'hobbies': ['street', 'read'], 'skills': {'te..."
998,999,Brittany Barrett,21,FEMALE,86,001-663-118-1327x207,Port Rachael,richardgreen@@shannon-jenkins.info,1625723463,data_sciense,110%,active,3.06,average,"238,00",2015.05.24,"25998 Martinez Grove Apt. 473, West Scott","{'hobbies': ['game', 'total'], 'skills': {'tec..."
999,1000,NaN,twenty,NaN,ninety,486.754.8735,Dariusborough,?ali@@gmail..com,1624533231,PYTHNO,70,inactive,four point five,excellent,224.0,27/06/2015 08:04 AM,"Apartment 24, Grossbury district, Tashkent, UZ...",INVALID_JSON_DATA

In [12]:
import numpy as np

In [13]:
# Replacing empty strings with NaN
df = df.replace("", np.nan)

In [14]:
df.isna().sum()

student_id        0
name            335
age             108
gender          219
score           246
phone           371
city              0
email           151
date_of_join      0
course            0
attendance      326
status            0
gpa             141
remarks         204
money_spent       0
event_time        0
address_raw       0
profile_json      0
dtype: int64

STEP 3: Cleaning numbers and dates

In [ ]:
numeric_columns = ['age', 'score','gpa','attendance', 'money_spent']

for col in numeric_columns:

  # Cleaning from symbols
  df[col] = df[col].astype(str).str.replace(r"[^0-9.-]", "", regex=True)

  # Convert to numeric, invalid values bacome NaN
  df[col] = pd.to_numeric(df[col], errors='coerce')

df.loc[df['age']<0, 'age'] = np.nan
df.loc[(df['gpa']<0) | (df['gpa']>5), 'gpa'] = np.nan
df.loc[(df['attendance']<0) | (df['attendance']>100), 'attendance'] = np.nan
df.loc[(df['score']<0) | (df['score']>100), 'score'] = np.nan
df.loc[df['money_spent']<0, 'money_spent'] = np.nan

df['age'] = df['age'].astype('Int64')
df['gpa'] = df['gpa'].astype(float)
df['attendance'] = df['attendance'].astype(float)
df['score'] = df['score'].astype(float)
df['money_spent'] = df['money_spent'].astype(float)

In [16]:
df

,student_id,name,age,gender,score,phone,city,email,date_of_join,course,attendance,status,gpa,remarks,money_spent,event_time,address_raw,profile_json
0,1,Claudia Short,20,NaN,NaN,+1-619-379-4152x102,Katieland,someonegmail.com,1662247364,Data Science,NaN,active,3.72,good,135.0,1629312830,"Apartment 37, South Kevin district, Tashkent, ...","{'hobbies': ['gun', 'nice'], 'skills': {'tech'..."
1,2,NaN,20,Female,NaN,NaN,Dawnburgh,psmith@chen.com,2017/08/29,Data Science,NaN,active,1.88,excellent,152.0,11/10/2001 04:19 AM,UZ 100332 Tashkent South Patricia,"{hobbies:['against', 'good']}"
2,3,Kathryn Moyer,20,NaN,NaN,NaN,Lake Stevenmouth,NaN,2017-08-14,DATA SCIENCE,NaN,pending,NaN,excellent,185.0,1657837622,"Wendyshire 12-kv, dom 1, Tashkent","{'hobbies': ['fast', 'clearly'], 'skills': {'t..."
3,4,Ruben Wilson,<NA>,fmale,81.0,NaN,Port Pamelafort,special,1973-09-17,data-sciens,NaN,inactive,0.00,good,175.0,1682795130,"Apartment 16, North Tamara district, Tashkent,...","{'hobbies': ['left', 'role'], 'skills': {'tech..."
4,5,Robert Pruitt,20,Female,NaN,001-182-659-5631x02803,Kingburgh,six,2023/11/25,data_sciense,NaN,pending,4.37,average,282.0,2013-10-13,"BROKEN,ADDRESS,DATA,,,","{'hobbies': ['sort', 'science'], 'skills': {'t..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Gary Sawyer,22,fmale,NaN,NaN,Gabriellefurt,amy97@woodard.net,1992.11.13,DATA SCIENCE,NaN,inactive,NaN,excellent,64.0,14/10/2007 06:53 PM,"Apartment 12, Laurenhaven district, Tashkent, ...","{'hobbies': ['collection', 'his'], 'skills': {..."
996,997,Scott Clark,20,NaN,NaN,001-205-065-8737,Rogerborough,katiepage@hensley.com,2024.10.05,DATA SCIENCE,NaN,pending,NaN,NaN,143.0,2021-06-21T07:46:27,"Patrickmouth 4-kv, dom 6, Tashkent",INVALID_JSON_DATA
997,998,NaN,20,MALE,NaN,264-577-8585,South Mary,someonegmail.com,19/11/2021 02:23 AM,data_sciense,95.0,inactive,NaN,excellent,79.0,1975/05/11,"Apartment 38, New Brendan district, Tashkent, ...","{'hobbies': ['street', 'read'], 'skills': {'te..."
998,999,Brittany Barrett,21,FEMALE,86.0,001-663-118-1327x207,Port Rachael,richardgreen@@shannon-jenkins.info,1625723463,data_sciense,NaN,active,3.06,average,23800.0,2015.05.24,"25998 Martinez Grove Apt. 473, West Scott","{'hobbies': ['game', 'total'], 'skills': {'tec..."
999,1000,NaN,<NA>,NaN,NaN,486.754.8735,Dariusborough,?ali@@gmail..com,1624533231,PYTHNO,70.0,inactive,NaN,excellent,224.0,27/06/2015 08:04 AM,"Apartment 24, Grossbury district, Tashkent, UZ...",INVALID_JSON_DATA

In [17]:
df.isna().sum()

student_id        0
name            335
age             226
gender          219
score           497
phone           371
city              0
email           151
date_of_join      0
course            0
attendance      773
status            0
gpa             730
remarks         204
money_spent       0
event_time        0
address_raw       0
profile_json      0
dtype: int64

In [18]:
# Converting date columns into pandas datetime format
date_columns = ['date_of_join', 'event_time']

for col in date_columns:
  df[col] = pd.to_datetime(df[col], errors='coerce')

  df[col] = df[col].dt.strftime("%Y-%m-%d %H:%M:%S")

C:\Users\TEMA\AppData\Local\Temp\ipykernel_17584\3934854237.py:5: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[col] = pd.to_datetime(df[col], errors='coerce')
C:\Users\TEMA\AppData\Local\Temp\ipykernel_17584\3934854237.py:5: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[col] = pd.to_datetime(df[col], errors='coerce')

In [19]:
df

,student_id,name,age,gender,score,phone,city,email,date_of_join,course,attendance,status,gpa,remarks,money_spent,event_time,address_raw,profile_json
0,1,Claudia Short,20,NaN,NaN,+1-619-379-4152x102,Katieland,someonegmail.com,NaN,Data Science,NaN,active,3.72,good,135.0,NaN,"Apartment 37, South Kevin district, Tashkent, ...","{'hobbies': ['gun', 'nice'], 'skills': {'tech'..."
1,2,NaN,20,Female,NaN,NaN,Dawnburgh,psmith@chen.com,2017-08-29 00:00:00,Data Science,NaN,active,1.88,excellent,152.0,2001-11-10 04:19:00,UZ 100332 Tashkent South Patricia,"{hobbies:['against', 'good']}"
2,3,Kathryn Moyer,20,NaN,NaN,NaN,Lake Stevenmouth,NaN,2017-08-14 00:00:00,DATA SCIENCE,NaN,pending,NaN,excellent,185.0,NaN,"Wendyshire 12-kv, dom 1, Tashkent","{'hobbies': ['fast', 'clearly'], 'skills': {'t..."
3,4,Ruben Wilson,<NA>,fmale,81.0,NaN,Port Pamelafort,special,1973-09-17 00:00:00,data-sciens,NaN,inactive,0.00,good,175.0,NaN,"Apartment 16, North Tamara district, Tashkent,...","{'hobbies': ['left', 'role'], 'skills': {'tech..."
4,5,Robert Pruitt,20,Female,NaN,001-182-659-5631x02803,Kingburgh,six,2023-11-25 00:00:00,data_sciense,NaN,pending,4.37,average,282.0,2013-10-13 00:00:00,"BROKEN,ADDRESS,DATA,,,","{'hobbies': ['sort', 'science'], 'skills': {'t..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Gary Sawyer,22,fmale,NaN,NaN,Gabriellefurt,amy97@woodard.net,1992-11-13 00:00:00,DATA SCIENCE,NaN,inactive,NaN,excellent,64.0,2007-10-14 18:53:00,"Apartment 12, Laurenhaven district, Tashkent, ...","{'hobbies': ['collection', 'his'], 'skills': {..."
996,997,Scott Clark,20,NaN,NaN,001-205-065-8737,Rogerborough,katiepage@hensley.com,2024-10-05 00:00:00,DATA SCIENCE,NaN,pending,NaN,NaN,143.0,2021-06-21 07:46:27,"Patrickmouth 4-kv, dom 6, Tashkent",INVALID_JSON_DATA
997,998,NaN,20,MALE,NaN,264-577-8585,South Mary,someonegmail.com,2021-11-19 02:23:00,data_sciense,95.0,inactive,NaN,excellent,79.0,1975-05-11 00:00:00,"Apartment 38, New Brendan district, Tashkent, ...","{'hobbies': ['street', 'read'], 'skills': {'te..."
998,999,Brittany Barrett,21,FEMALE,86.0,001-663-118-1327x207,Port Rachael,richardgreen@@shannon-jenkins.info,NaN,data_sciense,NaN,active,3.06,average,23800.0,2015-05-24 00:00:00,"25998 Martinez Grove Apt. 473, West Scott","{'hobbies': ['game', 'total'], 'skills': {'tec..."
999,1000,NaN,<NA>,NaN,NaN,486.754.8735,Dariusborough,?ali@@gmail..com,NaN,PYTHNO,70.0,inactive,NaN,excellent,224.0,2015-06-27 08:04:00,"Apartment 24, Grossbury district, Tashkent, UZ...",INVALID_JSON_DATA

STEP 4: Email and Phone validation

In [ ]:
# Making sure that empty or NaN stays as NaN
df['email'] = df['email'].replace(r'^\s*$', np.nan, regex=True)

# Stripping spaces
df['email'] = df['email'].str.strip()

# Turning emails into lowercase 
df['email'] = df['email'].str.lower()

# Regex for valid email
email_pattern = r'^[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$'

valid_mask = df['email'].str.match(email_pattern, na=False)

df.loc[~valid_mask, 'email'] = np.nan

In [21]:
df.head(20)

,student_id,name,age,gender,score,phone,city,email,date_of_join,course,attendance,status,gpa,remarks,money_spent,event_time,address_raw,profile_json
0,1,Claudia Short,20,NaN,NaN,+1-619-379-4152x102,Katieland,NaN,NaN,Data Science,NaN,active,3.72,good,135.0,NaN,"Apartment 37, South Kevin district, Tashkent, ...","{'hobbies': ['gun', 'nice'], 'skills': {'tech'..."
1,2,NaN,20,Female,NaN,NaN,Dawnburgh,psmith@chen.com,2017-08-29 00:00:00,Data Science,NaN,active,1.88,excellent,152.0,2001-11-10 04:19:00,UZ 100332 Tashkent South Patricia,"{hobbies:['against', 'good']}"
2,3,Kathryn Moyer,20,NaN,NaN,NaN,Lake Stevenmouth,NaN,2017-08-14 00:00:00,DATA SCIENCE,NaN,pending,NaN,excellent,185.0,NaN,"Wendyshire 12-kv, dom 1, Tashkent","{'hobbies': ['fast', 'clearly'], 'skills': {'t..."
3,4,Ruben Wilson,<NA>,fmale,81.0,NaN,Port Pamelafort,NaN,1973-09-17 00:00:00,data-sciens,NaN,inactive,0.00,good,175.0,NaN,"Apartment 16, North Tamara district, Tashkent,...","{'hobbies': ['left', 'role'], 'skills': {'tech..."
4,5,Robert Pruitt,20,Female,NaN,001-182-659-5631x02803,Kingburgh,NaN,2023-11-25 00:00:00,data_sciense,NaN,pending,4.37,average,282.0,2013-10-13 00:00:00,"BROKEN,ADDRESS,DATA,,,","{'hobbies': ['sort', 'science'], 'skills': {'t..."
5,6,David Martinez,20,Male,NaN,001-074-828-6016x937,Hugheshaven,nathangibbs@hotmail.com,NaN,DATA SCIENCE,NaN,pending,NaN,average,8500.0,1983-04-30 01:46:36,"Apartment 42, North Jamesfurt district, Tashke...","{hobbies:['order', 'keep']}"
6,7,NaN,18,FEMALE,71.0,314.018.0928x3134,Sharpfurt,NaN,1982-01-16 00:00:00,data science,NaN,active,0.00,excellent,275.0,2004-11-19 23:42:00,"Lake Tracishire 29-kv, dom 8, Tashkent","{'hobbies': ['fall', 'teacher'], 'skills': {'t..."
7,8,Nicholas Dennis,21,FEMALE,NaN,8091556011,Matthewfort,NaN,2000-06-26 00:00:00,python,63.0,active,NaN,excellent,135.0,1978-09-23 00:00:00,"70576 Butler Harbor Suite 847, Janetberg",INVALID_JSON_DATA
8,9,NaN,<NA>,fmale,77.0,854-964-5423,South Paulchester,stacysmith@taylor.biz,2000-03-15 00:00:00,ds,NaN,active,NaN,excellent,104.0,1995-10-20 00:00:00,"Williamsborough 2-kv, dom 18, Tashkent","{'hobbies': ['require', 'open'], 'skills': {'t..."
9,10,Elizabeth Villegas,22,femlae,NaN,(205)467-4476x0583,South Dianatown,NaN,2013-02-11 07:12:29,data_sciense,99.0,inactive,NaN,average,21500.0,2014-12-16 06:44:51,"BROKEN,ADDRESS,DATA,,,","{'hobbies': ['management', 'to'], 'skills': {'..."
10,11,Shawn Baker,19,NaN,NaN,9868509629,Zhangstad,NaN,2025-06-10 00:00:00,data science,NaN,active,NaN,excellent,18300.0,2001-06-06 05:29:47,"Apartment 34, North Samantha district, Tashken...",INVALID_JSON_DATA
11,12,NaN,18,femlae,71.0,NaN,Austinside,NaN,2013-01-14 19:16:00,d.s.,NaN,inactive,NaN,average,208.0,2003-05-27 00:00:00,"Apartment 13, Morrismouth district, Tashkent, ...","{hobbies:['forward', 'like']}"
12,13,NaN,19,fmale,NaN,(223)573-6311x916,Lesliefurt,NaN,2014-12-24 00:00:00,data science,NaN,inactive,NaN,excellent,84.0,2010-11-21 00:00:00,"Frankchester 9-kv, dom 20, Tashkent",INVALID_JSON_DATA
13,14,Thomas Prince,20,NaN,NaN,NaN,East Michellestad,aphillips@holland-diaz.org,2012-02-09 00:00:00,PYTHNO,NaN,inactive,NaN,excellent,210.0,2013-05-14 00:00:00,UZ 100394 Tashkent Stevensborough,"{hobbies:['understand', 'become']}"
14,15,NaN,21,MALE,73.0,NaN,Michellebury,kevin65@maxwell.info,1971-03-17 08:30:18,python,NaN,pending,NaN,good,191.0,1984-10-29 14:14:47,"Davidborough 9-kv, dom 29, Tashkent",INVALID_JSON_DATA
15,16,Adrian Allen,20,FEMALE,NaN,NaN,Antoniobury,NaN,1999-08-29 00:00:00,PYTHNO,NaN,pending,NaN,excellent,53.0,1983-10-13 00:00:00,"1965 Jacobs Branch Apt. 418, Timburgh","{'hobbies': ['partner', 'race'], 'skills': {'t..."
16,17,Stephen Lyons,19,NaN,76.0,NaN,New Adam,NaN,2009-10-13 02:20:00,data-sciens,NaN,active,NaN,good,110.0,1984-12-04 09:17:45,UZ 100399 Tashkent Joehaven,"{'hobbies': ['nothing', 'community'], 'skills'..."
17,18,Zachary Lyons,18,male,68.0,(242)552-5722,Chenport,NaN,2003-09-25 00:00:00,data_sciense,NaN,inactive,NaN,average,138.0,1997-08-27 00:00:00,"Apartment 22, Port Kevin district, Tashkent, U...",INVALID_JSON_DATA
18,19,NaN,20,fmale,50.0,+1-179-099-6883,West Danaville,NaN,1974-02-20 00:00:00,data_sciense,NaN,active,3.05,excellent,6600.0,1976-05-07 00:00:00,"BROKEN,ADDRESS,DATA,,,",INVALID_JSON_DATA
19,20,Anthony Hardy,20,male,NaN,669-272-8730x1241,Kimport,NaN,1973-05-20 19:05:00,ds,65.0,pending,NaN,excellent,218.0,NaN,"Masontown 10-kv, dom 21, Tashkent","{'hobbies': ['certainly', 'defense'], 'skills'..."

In [22]:
# cleaning phone numbers and converting them into standart form
df['phone'] = df['phone'].astype(str)

df['phone'] = df['phone'].str.replace(r'(ext|x|extension)\s*\d+', "", regex = True)
df['phone_clean'] = df['phone'].str.replace(r'\D',"", regex = True)

df['phone_clean'] = "+" + df['phone_clean']

# regex for phone number
phone_pattern =  r'^\+\d{8,15}$'

valid_mask = df['phone_clean'].str.len().between(9, 16)
df.loc[~valid_mask, 'phone_clean'] = np.nan

df['phone'] = df['phone_clean']
df.drop(columns=['phone_clean'], inplace= True)

In [23]:
df.head(20)

,student_id,name,age,gender,score,phone,city,email,date_of_join,course,attendance,status,gpa,remarks,money_spent,event_time,address_raw,profile_json
0,1,Claudia Short,20,NaN,NaN,+16193794152,Katieland,NaN,NaN,Data Science,NaN,active,3.72,good,135.0,NaN,"Apartment 37, South Kevin district, Tashkent, ...","{'hobbies': ['gun', 'nice'], 'skills': {'tech'..."
1,2,NaN,20,Female,NaN,NaN,Dawnburgh,psmith@chen.com,2017-08-29 00:00:00,Data Science,NaN,active,1.88,excellent,152.0,2001-11-10 04:19:00,UZ 100332 Tashkent South Patricia,"{hobbies:['against', 'good']}"
2,3,Kathryn Moyer,20,NaN,NaN,NaN,Lake Stevenmouth,NaN,2017-08-14 00:00:00,DATA SCIENCE,NaN,pending,NaN,excellent,185.0,NaN,"Wendyshire 12-kv, dom 1, Tashkent","{'hobbies': ['fast', 'clearly'], 'skills': {'t..."
3,4,Ruben Wilson,<NA>,fmale,81.0,NaN,Port Pamelafort,NaN,1973-09-17 00:00:00,data-sciens,NaN,inactive,0.00,good,175.0,NaN,"Apartment 16, North Tamara district, Tashkent,...","{'hobbies': ['left', 'role'], 'skills': {'tech..."
4,5,Robert Pruitt,20,Female,NaN,+0011826595631,Kingburgh,NaN,2023-11-25 00:00:00,data_sciense,NaN,pending,4.37,average,282.0,2013-10-13 00:00:00,"BROKEN,ADDRESS,DATA,,,","{'hobbies': ['sort', 'science'], 'skills': {'t..."
5,6,David Martinez,20,Male,NaN,+0010748286016,Hugheshaven,nathangibbs@hotmail.com,NaN,DATA SCIENCE,NaN,pending,NaN,average,8500.0,1983-04-30 01:46:36,"Apartment 42, North Jamesfurt district, Tashke...","{hobbies:['order', 'keep']}"
6,7,NaN,18,FEMALE,71.0,+3140180928,Sharpfurt,NaN,1982-01-16 00:00:00,data science,NaN,active,0.00,excellent,275.0,2004-11-19 23:42:00,"Lake Tracishire 29-kv, dom 8, Tashkent","{'hobbies': ['fall', 'teacher'], 'skills': {'t..."
7,8,Nicholas Dennis,21,FEMALE,NaN,+8091556011,Matthewfort,NaN,2000-06-26 00:00:00,python,63.0,active,NaN,excellent,135.0,1978-09-23 00:00:00,"70576 Butler Harbor Suite 847, Janetberg",INVALID_JSON_DATA
8,9,NaN,<NA>,fmale,77.0,+8549645423,South Paulchester,stacysmith@taylor.biz,2000-03-15 00:00:00,ds,NaN,active,NaN,excellent,104.0,1995-10-20 00:00:00,"Williamsborough 2-kv, dom 18, Tashkent","{'hobbies': ['require', 'open'], 'skills': {'t..."
9,10,Elizabeth Villegas,22,femlae,NaN,+2054674476,South Dianatown,NaN,2013-02-11 07:12:29,data_sciense,99.0,inactive,NaN,average,21500.0,2014-12-16 06:44:51,"BROKEN,ADDRESS,DATA,,,","{'hobbies': ['management', 'to'], 'skills': {'..."
10,11,Shawn Baker,19,NaN,NaN,+9868509629,Zhangstad,NaN,2025-06-10 00:00:00,data science,NaN,active,NaN,excellent,18300.0,2001-06-06 05:29:47,"Apartment 34, North Samantha district, Tashken...",INVALID_JSON_DATA
11,12,NaN,18,femlae,71.0,NaN,Austinside,NaN,2013-01-14 19:16:00,d.s.,NaN,inactive,NaN,average,208.0,2003-05-27 00:00:00,"Apartment 13, Morrismouth district, Tashkent, ...","{hobbies:['forward', 'like']}"
12,13,NaN,19,fmale,NaN,+2235736311,Lesliefurt,NaN,2014-12-24 00:00:00,data science,NaN,inactive,NaN,excellent,84.0,2010-11-21 00:00:00,"Frankchester 9-kv, dom 20, Tashkent",INVALID_JSON_DATA
13,14,Thomas Prince,20,NaN,NaN,NaN,East Michellestad,aphillips@holland-diaz.org,2012-02-09 00:00:00,PYTHNO,NaN,inactive,NaN,excellent,210.0,2013-05-14 00:00:00,UZ 100394 Tashkent Stevensborough,"{hobbies:['understand', 'become']}"
14,15,NaN,21,MALE,73.0,NaN,Michellebury,kevin65@maxwell.info,1971-03-17 08:30:18,python,NaN,pending,NaN,good,191.0,1984-10-29 14:14:47,"Davidborough 9-kv, dom 29, Tashkent",INVALID_JSON_DATA
15,16,Adrian Allen,20,FEMALE,NaN,NaN,Antoniobury,NaN,1999-08-29 00:00:00,PYTHNO,NaN,pending,NaN,excellent,53.0,1983-10-13 00:00:00,"1965 Jacobs Branch Apt. 418, Timburgh","{'hobbies': ['partner', 'race'], 'skills': {'t..."
16,17,Stephen Lyons,19,NaN,76.0,NaN,New Adam,NaN,2009-10-13 02:20:00,data-sciens,NaN,active,NaN,good,110.0,1984-12-04 09:17:45,UZ 100399 Tashkent Joehaven,"{'hobbies': ['nothing', 'community'], 'skills'..."
17,18,Zachary Lyons,18,male,68.0,+2425525722,Chenport,NaN,2003-09-25 00:00:00,data_sciense,NaN,inactive,NaN,average,138.0,1997-08-27 00:00:00,"Apartment 22, Port Kevin district, Tashkent, U...",INVALID_JSON_DATA
18,19,NaN,20,fmale,50.0,+11790996883,West Danaville,NaN,1974-02-20 00:00:00,data_sciense,NaN,active,3.05,excellent,6600.0,1976-05-07 00:00:00,"BROKEN,ADDRESS,DATA,,,",INVALID_JSON_DATA
19,20,Anthony Hardy,20,male,NaN,+6692728730,Kimport,NaN,1973-05-20 19:05:00,ds,65.0,pending,NaN,excellent,218.0,NaN,"Masontown 10-kv, dom 21, Tashkent","{'hobbies': ['certainly', 'defense'], 'skills'..."

STEP 5: JSON Parsing

In [24]:
import json

In [ ]:
# Conversting Json into Python dictionary

df['profile_json'] = df['profile_json'].astype(str).str.replace("'",'"', regex = False)

def json_parse(x):
  try:
    return json.loads(x)
  except:
    return {}
  
df['profile_json'] = df['profile_json'].apply(json_parse)

In [26]:
df

,student_id,name,age,gender,score,phone,city,email,date_of_join,course,attendance,status,gpa,remarks,money_spent,event_time,address_raw,profile_json
0,1,Claudia Short,20,NaN,NaN,+16193794152,Katieland,NaN,NaN,Data Science,NaN,active,3.72,good,135.0,NaN,"Apartment 37, South Kevin district, Tashkent, ...","{'hobbies': ['gun', 'nice'], 'skills': {'tech'..."
1,2,NaN,20,Female,NaN,NaN,Dawnburgh,psmith@chen.com,2017-08-29 00:00:00,Data Science,NaN,active,1.88,excellent,152.0,2001-11-10 04:19:00,UZ 100332 Tashkent South Patricia,{}
2,3,Kathryn Moyer,20,NaN,NaN,NaN,Lake Stevenmouth,NaN,2017-08-14 00:00:00,DATA SCIENCE,NaN,pending,NaN,excellent,185.0,NaN,"Wendyshire 12-kv, dom 1, Tashkent","{'hobbies': ['fast', 'clearly'], 'skills': {'t..."
3,4,Ruben Wilson,<NA>,fmale,81.0,NaN,Port Pamelafort,NaN,1973-09-17 00:00:00,data-sciens,NaN,inactive,0.00,good,175.0,NaN,"Apartment 16, North Tamara district, Tashkent,...","{'hobbies': ['left', 'role'], 'skills': {'tech..."
4,5,Robert Pruitt,20,Female,NaN,+0011826595631,Kingburgh,NaN,2023-11-25 00:00:00,data_sciense,NaN,pending,4.37,average,282.0,2013-10-13 00:00:00,"BROKEN,ADDRESS,DATA,,,","{'hobbies': ['sort', 'science'], 'skills': {'t..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Gary Sawyer,22,fmale,NaN,NaN,Gabriellefurt,amy97@woodard.net,1992-11-13 00:00:00,DATA SCIENCE,NaN,inactive,NaN,excellent,64.0,2007-10-14 18:53:00,"Apartment 12, Laurenhaven district, Tashkent, ...","{'hobbies': ['collection', 'his'], 'skills': {..."
996,997,Scott Clark,20,NaN,NaN,+0012050658737,Rogerborough,katiepage@hensley.com,2024-10-05 00:00:00,DATA SCIENCE,NaN,pending,NaN,NaN,143.0,2021-06-21 07:46:27,"Patrickmouth 4-kv, dom 6, Tashkent",{}
997,998,NaN,20,MALE,NaN,+2645778585,South Mary,NaN,2021-11-19 02:23:00,data_sciense,95.0,inactive,NaN,excellent,79.0,1975-05-11 00:00:00,"Apartment 38, New Brendan district, Tashkent, ...","{'hobbies': ['street', 'read'], 'skills': {'te..."
998,999,Brittany Barrett,21,FEMALE,86.0,+0016631181327,Port Rachael,NaN,NaN,data_sciense,NaN,active,3.06,average,23800.0,2015-05-24 00:00:00,"25998 Martinez Grove Apt. 473, West Scott","{'hobbies': ['game', 'total'], 'skills': {'tec..."
999,1000,NaN,<NA>,NaN,NaN,+4867548735,Dariusborough,NaN,NaN,PYTHNO,70.0,inactive,NaN,excellent,224.0,2015-06-27 08:04:00,"Apartment 24, Grossbury district, Tashkent, UZ...",{}

In [27]:
# Flatten Json into columns

json_df = pd.json_normalize(df['profile_json'])

In [28]:
df = pd.concat([df.drop(columns=['profile_json']), json_df], axis = 1)

In [29]:
df.head(20)

,student_id,name,age,gender,score,phone,city,email,date_of_join,course,...,address_raw,hobbies,devices,skills.tech.python,skills.tech.excel,skills.tech.sql,skills.soft,family.siblings,family.income.father,family.income.mother
0,1,Claudia Short,20,NaN,NaN,+16193794152,Katieland,NaN,NaN,Data Science,...,"Apartment 37, South Kevin district, Tashkent, ...","[gun, nice]","[{'type': 'laptop', 'brand': 'HP', 'year': 202...",2.0,5.0,1.0,"[with, onto]",4.0,1198.0,1089.0
1,2,NaN,20,Female,NaN,NaN,Dawnburgh,psmith@chen.com,2017-08-29 00:00:00,Data Science,...,UZ 100332 Tashkent South Patricia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,Kathryn Moyer,20,NaN,NaN,NaN,Lake Stevenmouth,NaN,2017-08-14 00:00:00,DATA SCIENCE,...,"Wendyshire 12-kv, dom 1, Tashkent","[fast, clearly]","[{'type': 'laptop', 'brand': 'HP', 'year': 202...",5.0,3.0,1.0,"[despite, clearly]",1.0,263.0,202.0
3,4,Ruben Wilson,<NA>,fmale,81.0,NaN,Port Pamelafort,NaN,1973-09-17 00:00:00,data-sciens,...,"Apartment 16, North Tamara district, Tashkent,...","[left, role]","[{'type': 'laptop', 'brand': 'Lenovo', 'year':...",3.0,5.0,1.0,"[full, series]",4.0,508.0,698.0
4,5,Robert Pruitt,20,Female,NaN,+0011826595631,Kingburgh,NaN,2023-11-25 00:00:00,data_sciense,...,"BROKEN,ADDRESS,DATA,,,","[sort, science]","[{'type': 'laptop', 'brand': 'Lenovo', 'year':...",1.0,4.0,1.0,"[whose, save]",3.0,862.0,1058.0
5,6,David Martinez,20,Male,NaN,+0010748286016,Hugheshaven,nathangibbs@hotmail.com,NaN,DATA SCIENCE,...,"Apartment 42, North Jamesfurt district, Tashke...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,7,NaN,18,FEMALE,71.0,+3140180928,Sharpfurt,NaN,1982-01-16 00:00:00,data science,...,"Lake Tracishire 29-kv, dom 8, Tashkent","[fall, teacher]","[{'type': 'laptop', 'brand': 'HP', 'year': 201...",4.0,1.0,4.0,"[teacher, good]",3.0,1270.0,931.0
7,8,Nicholas Dennis,21,FEMALE,NaN,+8091556011,Matthewfort,NaN,2000-06-26 00:00:00,python,...,"70576 Butler Harbor Suite 847, Janetberg",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,9,NaN,<NA>,fmale,77.0,+8549645423,South Paulchester,stacysmith@taylor.biz,2000-03-15 00:00:00,ds,...,"Williamsborough 2-kv, dom 18, Tashkent","[require, open]","[{'type': 'laptop', 'brand': 'Dell', 'year': 2...",1.0,5.0,4.0,"[partner, walk]",0.0,850.0,1062.0
9,10,Elizabeth Villegas,22,femlae,NaN,+2054674476,South Dianatown,NaN,2013-02-11 07:12:29,data_sciense,...,"BROKEN,ADDRESS,DATA,,,","[management, to]","[{'type': 'laptop', 'brand': 'Dell', 'year': 2...",1.0,1.0,4.0,"[beat, southern]",3.0,597.0,1150.0
10,11,Shawn Baker,19,NaN,NaN,+9868509629,Zhangstad,NaN,2025-06-10 00:00:00,data science,...,"Apartment 34, North Samantha district, Tashken...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,12,NaN,18,femlae,71.0,NaN,Austinside,NaN,2013-01-14 19:16:00,d.s.,...,"Apartment 13, Morrismouth district, Tashkent, ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,13,NaN,19,fmale,NaN,+2235736311,Lesliefurt,NaN,2014-12-24 00:00:00,data science,...,"Frankchester 9-kv, dom 20, Tashkent",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,14,Thomas Prince,20,NaN,NaN,NaN,East Michellestad,aphillips@holland-diaz.org,2012-02-09 00:00:00,PYTHNO,...,UZ 100394 Tashkent Stevensborough,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,15,NaN,21,MALE,73.0,NaN,Michellebury,kevin65@maxwell.info,1971-03-17 08:30:18,python,...,"Davidborough 9-kv, dom 29, Tashkent",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,16,Adrian Allen,20,FEMALE,NaN,NaN,Antoniobury,NaN,1999-08-29 00:00:00,PYTHNO,...,"1965 Jacobs Branch Apt. 418, Timburgh","[partner, race]","[{'type': 'laptop', 'brand': 'Dell', 'year': 2...",4.0,4.0,4.0,"[onto, owner]",3.0,798.0,626.0
16,17,Stephen Lyons,19,NaN,76.0,NaN,New Adam,NaN,2009-10-13 02:20:00,data-sciens,...,UZ 100399 Tashkent Joehaven,"[nothing, community]","[{'type': 'laptop', 'brand': 'Lenovo', 'year':...",1.0,1.0,5.0,"[wear, will]",1.0,772.0,498.0
17,18,Zachary Lyons,18,male,68.0,+2425525722,Chenport,NaN,2003-09-25 00:00:00,data_sciense,...,"Apartment 22, Port Kevin district, Tashkent, U...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,19,NaN,20,fmale,50.0,+11790996883,West Danaville,NaN,1974-02-20 00:00:00,data_sciense,...,"BROKEN,ADDRESS,DATA,,,",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,20,Anthony Hardy,20,male,NaN,+6692728730,Kimport,NaN,1973-05-20 19:05:00,ds,...,"Masontown 10-kv, dom 21, Tashkent","[certainly, defense]","[{'type': 'laptop', 'brand': 'Lenovo', 'year':...",5.0,2.0,4.0,"[medical, quality]",4.0,1220.0,1220.0

In [30]:
def flatten_devices(devices_list):
  result = {}

  if isinstance(devices_list, list):
    for i, device in enumerate(devices_list):
      for key, value in device.items():
        result[f"device{i+1}_{key}"] = value

  return result

In [ ]:
names = ['alex','brown','tom']

for i, name in enumerate(names):
  print(f"{i} {name}")

0 alex
1 brown
2 tom

In [31]:
devices_expanded = df['devices'].apply(flatten_devices).apply(pd.Series)

In [32]:
df = pd.concat([df.drop(columns = ['devices']), devices_expanded], axis=1)

In [33]:
df.head(10)

,student_id,name,age,gender,score,phone,city,email,date_of_join,course,...,skills.soft,family.siblings,family.income.father,family.income.mother,device1_type,device1_brand,device1_year,device2_type,device2_brand,device2_year
0,1,Claudia Short,20,NaN,NaN,+16193794152,Katieland,NaN,NaN,Data Science,...,"[with, onto]",4.0,1198.0,1089.0,laptop,HP,2021.0,phone,Xiaomi,2021.0
1,2,NaN,20,Female,NaN,NaN,Dawnburgh,psmith@chen.com,2017-08-29 00:00:00,Data Science,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,Kathryn Moyer,20,NaN,NaN,NaN,Lake Stevenmouth,NaN,2017-08-14 00:00:00,DATA SCIENCE,...,"[despite, clearly]",1.0,263.0,202.0,laptop,HP,2020.0,phone,Samsung,2023.0
3,4,Ruben Wilson,<NA>,fmale,81.0,NaN,Port Pamelafort,NaN,1973-09-17 00:00:00,data-sciens,...,"[full, series]",4.0,508.0,698.0,laptop,Lenovo,2020.0,phone,Samsung,2024.0
4,5,Robert Pruitt,20,Female,NaN,+0011826595631,Kingburgh,NaN,2023-11-25 00:00:00,data_sciense,...,"[whose, save]",3.0,862.0,1058.0,laptop,Lenovo,2023.0,phone,Apple,2022.0
5,6,David Martinez,20,Male,NaN,+0010748286016,Hugheshaven,nathangibbs@hotmail.com,NaN,DATA SCIENCE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,7,NaN,18,FEMALE,71.0,+3140180928,Sharpfurt,NaN,1982-01-16 00:00:00,data science,...,"[teacher, good]",3.0,1270.0,931.0,laptop,HP,2018.0,phone,Xiaomi,2023.0
7,8,Nicholas Dennis,21,FEMALE,NaN,+8091556011,Matthewfort,NaN,2000-06-26 00:00:00,python,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,9,NaN,<NA>,fmale,77.0,+8549645423,South Paulchester,stacysmith@taylor.biz,2000-03-15 00:00:00,ds,...,"[partner, walk]",0.0,850.0,1062.0,laptop,Dell,2019.0,phone,Apple,2020.0
9,10,Elizabeth Villegas,22,femlae,NaN,+2054674476,South Dianatown,NaN,2013-02-11 07:12:29,data_sciense,...,"[beat, southern]",3.0,597.0,1150.0,laptop,Dell,2016.0,phone,Xiaomi,2023.0

In [34]:
df['hobbies']

0            [gun, nice]
1                    NaN
2        [fast, clearly]
3           [left, role]
4        [sort, science]
             ...
995    [collection, his]
996                  NaN
997       [street, read]
998        [game, total]
999                  NaN
Name: hobbies, Length: 1000, dtype: object

STEP 6: Address Parsing

In [35]:
import re

In [36]:
df['addr_postal'] = df['address_raw'].str.extract(r'(\d{5,6})')

In [37]:
df['addr_city'] = df['address_raw'].str.extract(r',\s*([^,]+),\s*UZ')[0]

df['addr_city'] = df['addr_city'].fillna(df['address_raw'].str.extract(r',\s*([^,]+)$')[0])

In [38]:
df['addr_district'] = df['address_raw'].str.extract(r'([^,]*district)')

In [39]:
df.head(10)

,student_id,name,age,gender,score,phone,city,email,date_of_join,course,...,family.income.mother,device1_type,device1_brand,device1_year,device2_type,device2_brand,device2_year,addr_postal,addr_city,addr_district
0,1,Claudia Short,20,NaN,NaN,+16193794152,Katieland,NaN,NaN,Data Science,...,1089.0,laptop,HP,2021.0,phone,Xiaomi,2021.0,100539,Tashkent,South Kevin district
1,2,NaN,20,Female,NaN,NaN,Dawnburgh,psmith@chen.com,2017-08-29 00:00:00,Data Science,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100332,NaN,NaN
2,3,Kathryn Moyer,20,NaN,NaN,NaN,Lake Stevenmouth,NaN,2017-08-14 00:00:00,DATA SCIENCE,...,202.0,laptop,HP,2020.0,phone,Samsung,2023.0,NaN,Tashkent,NaN
3,4,Ruben Wilson,<NA>,fmale,81.0,NaN,Port Pamelafort,NaN,1973-09-17 00:00:00,data-sciens,...,698.0,laptop,Lenovo,2020.0,phone,Samsung,2024.0,100097,Tashkent,North Tamara district
4,5,Robert Pruitt,20,Female,NaN,+0011826595631,Kingburgh,NaN,2023-11-25 00:00:00,data_sciense,...,1058.0,laptop,Lenovo,2023.0,phone,Apple,2022.0,NaN,NaN,NaN
5,6,David Martinez,20,Male,NaN,+0010748286016,Hugheshaven,nathangibbs@hotmail.com,NaN,DATA SCIENCE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100551,Tashkent,North Jamesfurt district
6,7,NaN,18,FEMALE,71.0,+3140180928,Sharpfurt,NaN,1982-01-16 00:00:00,data science,...,931.0,laptop,HP,2018.0,phone,Xiaomi,2023.0,NaN,Tashkent,NaN
7,8,Nicholas Dennis,21,FEMALE,NaN,+8091556011,Matthewfort,NaN,2000-06-26 00:00:00,python,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,70576,Janetberg,NaN
8,9,NaN,<NA>,fmale,77.0,+8549645423,South Paulchester,stacysmith@taylor.biz,2000-03-15 00:00:00,ds,...,1062.0,laptop,Dell,2019.0,phone,Apple,2020.0,NaN,Tashkent,NaN
9,10,Elizabeth Villegas,22,femlae,NaN,+2054674476,South Dianatown,NaN,2013-02-11 07:12:29,data_sciense,...,1150.0,laptop,Dell,2016.0,phone,Xiaomi,2023.0,NaN,NaN,NaN

In [40]:
df['address_raw']

0      Apartment 37, South Kevin district, Tashkent, ...
1                      UZ 100332 Tashkent South Patricia
2                      Wendyshire 12-kv, dom 1, Tashkent
3      Apartment 16, North Tamara district, Tashkent,...
4                                 BROKEN,ADDRESS,DATA,,,
                             ...
995    Apartment 12, Laurenhaven district, Tashkent, ...
996                   Patrickmouth 4-kv, dom 6, Tashkent
997    Apartment 38, New Brendan district, Tashkent, ...
998            25998 Martinez Grove Apt. 473, West Scott
999    Apartment 24, Grossbury district, Tashkent, UZ...
Name: address_raw, Length: 1000, dtype: str

STEP 7: Checking duplicate rows and missing data

In [41]:
df.duplicated(subset='student_id').sum()

np.int64(0)

In [42]:
df.isna().sum()

student_id                0
name                    335
age                     226
gender                  219
score                   497
phone                   371
city                      0
email                   714
date_of_join            177
course                    0
attendance              773
status                    0
gpa                     730
remarks                 204
money_spent               0
event_time              161
address_raw               0
hobbies                 406
skills.tech.python      406
skills.tech.excel       406
skills.tech.sql         406
skills.soft             406
family.siblings         406
family.income.father    406
family.income.mother    406
device1_type            406
device1_brand           406
device1_year            406
device2_type            406
device2_brand           406
device2_year            406
addr_postal             511
addr_city               405
addr_district           797
dtype: int64

In [43]:

fill_values = {
    'name': 'Unknown',
    'age': 0,
    'gender': 'Unknown',
    'score': 0,
    'phone': 'Unknown',
    'city': 'Unknown',
    'email': 'Unknown',
    'date_of_join': pd.NaT,       
    'course': 'Unknown',
    'attendance': 0,
    'status': 'Unknown',
    'gpa': 0.0,
    'remarks': 'None',
    'money_spent': 0.0,
    'event_time': pd.NaT,
    'addr_city': 'Unknown',
    'addr_district': 'Unknown',
    'addr_postal': 'Unknown'
}

df.fillna(value=fill_values, inplace=True)

,student_id,name,age,gender,score,phone,city,email,date_of_join,course,...,family.income.mother,device1_type,device1_brand,device1_year,device2_type,device2_brand,device2_year,addr_postal,addr_city,addr_district
0,1,Claudia Short,20,Unknown,0.0,+16193794152,Katieland,Unknown,NaN,Data Science,...,1089.0,laptop,HP,2021.0,phone,Xiaomi,2021.0,100539,Tashkent,South Kevin district
1,2,Unknown,20,Female,0.0,Unknown,Dawnburgh,psmith@chen.com,2017-08-29 00:00:00,Data Science,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100332,Unknown,Unknown
2,3,Kathryn Moyer,20,Unknown,0.0,Unknown,Lake Stevenmouth,Unknown,2017-08-14 00:00:00,DATA SCIENCE,...,202.0,laptop,HP,2020.0,phone,Samsung,2023.0,Unknown,Tashkent,Unknown
3,4,Ruben Wilson,0,fmale,81.0,Unknown,Port Pamelafort,Unknown,1973-09-17 00:00:00,data-sciens,...,698.0,laptop,Lenovo,2020.0,phone,Samsung,2024.0,100097,Tashkent,North Tamara district
4,5,Robert Pruitt,20,Female,0.0,+0011826595631,Kingburgh,Unknown,2023-11-25 00:00:00,data_sciense,...,1058.0,laptop,Lenovo,2023.0,phone,Apple,2022.0,Unknown,Unknown,Unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Gary Sawyer,22,fmale,0.0,Unknown,Gabriellefurt,amy97@woodard.net,1992-11-13 00:00:00,DATA SCIENCE,...,1335.0,laptop,Dell,2017.0,phone,Xiaomi,2019.0,100254,Tashkent,Laurenhaven district
996,997,Scott Clark,20,Unknown,0.0,+0012050658737,Rogerborough,katiepage@hensley.com,2024-10-05 00:00:00,DATA SCIENCE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown,Tashkent,Unknown
997,998,Unknown,20,MALE,0.0,+2645778585,South Mary,Unknown,2021-11-19 02:23:00,data_sciense,...,1005.0,laptop,HP,2020.0,phone,Xiaomi,2024.0,100394,Tashkent,New Brendan district
998,999,Brittany Barrett,21,FEMALE,86.0,+0016631181327,Port Rachael,Unknown,NaN,data_sciense,...,571.0,laptop,Dell,2022.0,phone,Samsung,2019.0,25998,West Scott,Unknown
999,1000,Unknown,0,Unknown,0.0,+4867548735,Dariusborough,Unknown,NaN,PYTHNO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100222,Tashkent,Grossbury district

STEP 8: Data Normalization

In [44]:
def normalize_gender(x):
  x = str(x).strip().lower()
  if x in ['male','m']:
    return 'Male'
  elif x in ['female','f','fmale']:
    return 'Female'
  else:
    return 'Unknown'
  
df['gender'] = df['gender'].apply(normalize_gender)

In [45]:
def normalize_course(x):
  x = str(x).strip().lower()
  if 'data' in x and 'science' in x:
    return 'Data Science'
  elif 'python' in x:
    return 'Python'
  else:
    return 'Unknown'
  
df['course'] = df['course'].apply(normalize_course)

In [46]:
df['status'] = df['status'].astype(str).str.strip().str.lower()

In [59]:
df.head(20)

,student_id,name,age,gender,score,phone,city,email,date_of_join,course,...,family.income.mother,device1_type,device1_brand,device1_year,device2_type,device2_brand,device2_year,addr_postal,addr_city,addr_district
0,1,Claudia Short,20,Unknown,0.0,+16193794152,Katieland,Unknown,NaN,Data Science,...,1089.0,laptop,HP,2021.0,phone,Xiaomi,2021.0,100539,Tashkent,South Kevin district
1,2,Unknown,20,Female,0.0,Unknown,Dawnburgh,psmith@chen.com,2017-08-29 00:00:00,Data Science,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100332,Unknown,Unknown
2,3,Kathryn Moyer,20,Unknown,0.0,Unknown,Lake Stevenmouth,Unknown,2017-08-14 00:00:00,Data Science,...,202.0,laptop,HP,2020.0,phone,Samsung,2023.0,Unknown,Tashkent,Unknown
3,4,Ruben Wilson,0,Female,81.0,Unknown,Port Pamelafort,Unknown,1973-09-17 00:00:00,Unknown,...,698.0,laptop,Lenovo,2020.0,phone,Samsung,2024.0,100097,Tashkent,North Tamara district
4,5,Robert Pruitt,20,Female,0.0,+0011826595631,Kingburgh,Unknown,2023-11-25 00:00:00,Unknown,...,1058.0,laptop,Lenovo,2023.0,phone,Apple,2022.0,Unknown,Unknown,Unknown
5,6,David Martinez,20,Male,0.0,+0010748286016,Hugheshaven,nathangibbs@hotmail.com,NaN,Data Science,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100551,Tashkent,North Jamesfurt district
6,7,Unknown,18,Female,71.0,+3140180928,Sharpfurt,Unknown,1982-01-16 00:00:00,Data Science,...,931.0,laptop,HP,2018.0,phone,Xiaomi,2023.0,Unknown,Tashkent,Unknown
7,8,Nicholas Dennis,21,Female,0.0,+8091556011,Matthewfort,Unknown,2000-06-26 00:00:00,Python,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,70576,Janetberg,Unknown
8,9,Unknown,0,Female,77.0,+8549645423,South Paulchester,stacysmith@taylor.biz,2000-03-15 00:00:00,Unknown,...,1062.0,laptop,Dell,2019.0,phone,Apple,2020.0,Unknown,Tashkent,Unknown
9,10,Elizabeth Villegas,22,Unknown,0.0,+2054674476,South Dianatown,Unknown,2013-02-11 07:12:29,Unknown,...,1150.0,laptop,Dell,2016.0,phone,Xiaomi,2023.0,Unknown,Unknown,Unknown
10,11,Shawn Baker,19,Unknown,0.0,+9868509629,Zhangstad,Unknown,2025-06-10 00:00:00,Data Science,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100659,Tashkent,North Samantha district
11,12,Unknown,18,Unknown,71.0,Unknown,Austinside,Unknown,2013-01-14 19:16:00,Unknown,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100315,Tashkent,Morrismouth district
12,13,Unknown,19,Female,0.0,+2235736311,Lesliefurt,Unknown,2014-12-24 00:00:00,Data Science,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown,Tashkent,Unknown
13,14,Thomas Prince,20,Unknown,0.0,Unknown,East Michellestad,aphillips@holland-diaz.org,2012-02-09 00:00:00,Unknown,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100394,Unknown,Unknown
14,15,Unknown,21,Male,73.0,Unknown,Michellebury,kevin65@maxwell.info,1971-03-17 08:30:18,Python,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown,Tashkent,Unknown
15,16,Adrian Allen,20,Female,0.0,Unknown,Antoniobury,Unknown,1999-08-29 00:00:00,Unknown,...,626.0,laptop,Dell,2019.0,phone,Apple,2022.0,Unknown,Timburgh,Unknown
16,17,Stephen Lyons,19,Unknown,76.0,Unknown,New Adam,Unknown,2009-10-13 02:20:00,Unknown,...,498.0,laptop,Lenovo,2023.0,phone,Apple,2021.0,100399,Unknown,Unknown
17,18,Zachary Lyons,18,Male,68.0,+2425525722,Chenport,Unknown,2003-09-25 00:00:00,Unknown,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100106,Tashkent,Port Kevin district
18,19,Unknown,20,Female,50.0,+11790996883,West Danaville,Unknown,1974-02-20 00:00:00,Unknown,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown,Unknown,Unknown
19,20,Anthony Hardy,20,Male,0.0,+6692728730,Kimport,Unknown,1973-05-20 19:05:00,Unknown,...,1220.0,laptop,Lenovo,2018.0,phone,Apple,2019.0,Unknown,Tashkent,Unknown

STEP 9: Final type conversion va export

In [50]:
df.dtypes

student_id                int64
name                        str
age                       Int64
gender                      str
score                   float64
phone                       str
city                        str
email                       str
date_of_join                str
course                      str
attendance              float64
status                      str
gpa                     float64
remarks                     str
money_spent             float64
event_time                  str
address_raw                 str
hobbies                  object
skills.tech.python      float64
skills.tech.excel       float64
skills.tech.sql         float64
skills.soft              object
family.siblings         float64
family.income.father    float64
family.income.mother    float64
device1_type                str
device1_brand               str
device1_year            float64
device2_type                str
device2_brand               str
device2_year            float64
addr_postal                 str
addr_city                   str
addr_district               str
dtype: object

In [51]:
# Export to CSV
df.to_csv('super_dirty_students_cleaned.csv', index=False)

print("Cleaned data saved to 'super_dirty_students_cleaned.csv'.")

Cleaned data saved to 'super_dirty_students_cleaned.csv'.

STEP 10: QA checks

In [52]:
df_original = pd.read_csv(r'd:\PythonCourse_MAAB\project\super_dirty_students_data.csv')
len(df_original.columns)

18

In [53]:
len(df.columns)

34

In [60]:
df.duplicated(subset='student_id').sum()

np.int64(0)

In [61]:
df['email'].isna().sum()

np.int64(0)

In [62]:
df['phone'].isna().sum()

np.int64(0)

In [58]:
# Define numeric columns and their valid ranges
numeric_ranges = {
    'gpa': (0, 5),
    'attendance': (0, 100),
    'score': (0, 100),
    'age': (0, 120),           # optional sanity check
    'money_spent': (0, None)   # only non-negative
}

for col, (min_val, max_val) in numeric_ranges.items():
    if max_val is not None:
        invalid = df[(df[col] < min_val) | (df[col] > max_val)]
    else:
        invalid = df[df[col] < min_val]
    print(f"{col} invalid rows: {len(invalid)}")

gpa invalid rows: 0
attendance invalid rows: 0
score invalid rows: 0
age invalid rows: 0
money_spent invalid rows: 0